Add GitHub fork me ribbon
manu-chroma/username-availability-checker pull request #138
Opened 2018-11-06 09:52 UTC by Chirag0111

Closes https://github.com/manu-chroma/username-availability-checker

2018-11-06 13:11 UTC, utkarsh2102 requested changes
Hey,
- Changes you made aren't really working. Did you test them locally?
- If possible, let's work on the commit message and mend it as per the [guidelines](https://coala.io/commit).
- Also, indent the code properly. That really helps.
- Include the snippets of the local test in the comments before submitting it for the review again. We'd know if that works ;)
- I'm extending the deadline by 24 hours. Please submit the same at the earliest. 
- Ping me on Gitter, Zulip or Telegram, if you need any help.

2018-11-06 13:55 UTC, manu-chroma commented
this is duplicated code from ``status.html``

We can avoid duplicating by refactoring github icon css into main css file.

2018-11-08 14:27 UTC, utkarsh2102 approved these changes
Except for changing the branch, the changes look good to me.
I think he's having a little trouble with rebasing, that won't be a problem, I guess.
Also, the line exceeds by the usual length, but that's okay, I guess?
The changes are working fine.

2018-11-08 15:15 UTC, li-boxuan commented on templates/form.html
> +
Unnecessary change?

2018-11-08 16:01 UTC, manu-chroma requested changes
github ribbon css is present in both ``status.html`` and ``form.html``

Please extract it out to ``main.css``

2018-11-09 23:29 UTC, Chirag0111 commented
@utkarsh2102, I have done the work.
- Added proper indentation, as asked by @utkarsh2102 and @jayvdb.
- Extracted css to `main.css`.

Please check the same.

2018-11-09 23:41 UTC, utkarsh2102 requested changes
I can't seem to find the hover effect working when tested locally.
Over to @manu-chroma.
Indentation looks fine now.

2018-11-10 08:22 UTC, manu-chroma approved these changes

2018-11-10 15:52 UTC, utkarsh2102 commented
Oh, that's awesome.
I will ask him to do so and would approve the task once he submits the same.

2018-11-10 16:16 UTC, Chirag0111 commented
Approved.

2018-11-10 16:18 UTC, Chirag0111 commented
Done.

![image](https://user-images.githubusercontent.com/40314084/48303624-514e1f80-e532-11e8-95c7-b8e2bd14155f.png)

2018-11-10 18:59 UTC, merged

2018-11-10 18:59 UTC, manu-chroma commented
:tada: